version: '3.9'

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=solid_user
      - POSTGRES_DB=solid

volumes:
  db_data:
